-- VakantieTeller database
-- Voer dit hele bestand één keer uit in Supabase, SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.players (
  id uuid primary key default gen_random_uuid(),
  name text not null unique check (char_length(name) between 1 and 40),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.drinks (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.players(id) on delete restrict,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  drink_type text not null check (
    drink_type in ('bier', 'wijn', 'cocktail', 'shot', 'fris', 'water')
  ),
  created_at timestamptz not null default now()
);

create index if not exists drinks_player_id_idx
  on public.drinks(player_id);

create index if not exists drinks_created_at_idx
  on public.drinks(created_at desc);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.admins
    where user_id = (select auth.uid())
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

alter table public.players enable row level security;
alter table public.profiles enable row level security;
alter table public.admins enable row level security;
alter table public.drinks enable row level security;

drop policy if exists "Authenticated users can read players" on public.players;
create policy "Authenticated users can read players"
on public.players
for select
to authenticated
using (true);

drop policy if exists "Admins can add players" on public.players;
create policy "Admins can add players"
on public.players
for insert
to authenticated
with check ((select public.is_admin()));

drop policy if exists "Admins can update players" on public.players;
create policy "Admins can update players"
on public.players
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "Admins can delete players" on public.players;
create policy "Admins can delete players"
on public.players
for delete
to authenticated
using ((select public.is_admin()));

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
on public.profiles
for select
to authenticated
using (
  user_id = (select auth.uid())
  or (select public.is_admin())
);

drop policy if exists "Users can create own profile" on public.profiles;
create policy "Users can create own profile"
on public.profiles
for insert
to authenticated
with check (
  user_id = (select auth.uid())
  and exists (
    select 1
    from public.players
    where players.id = profiles.player_id
      and players.active = true
  )
);

drop policy if exists "Users can change own profile" on public.profiles;
create policy "Users can change own profile"
on public.profiles
for update
to authenticated
using (
  user_id = (select auth.uid())
  or (select public.is_admin())
)
with check (
  (
    user_id = (select auth.uid())
    or (select public.is_admin())
  )
  and exists (
    select 1
    from public.players
    where players.id = profiles.player_id
      and players.active = true
  )
);

drop policy if exists "Admins can delete profiles" on public.profiles;
create policy "Admins can delete profiles"
on public.profiles
for delete
to authenticated
using ((select public.is_admin()));

drop policy if exists "No direct admin table reads" on public.admins;
create policy "No direct admin table reads"
on public.admins
for select
to authenticated
using (false);

drop policy if exists "Authenticated users can read drinks" on public.drinks;
create policy "Authenticated users can read drinks"
on public.drinks
for select
to authenticated
using (true);

drop policy if exists "Players can add their own drinks" on public.drinks;
create policy "Players can add their own drinks"
on public.drinks
for insert
to authenticated
with check (
  owner_user_id = (select auth.uid())
  and player_id = (
    select profiles.player_id
    from public.profiles
    where profiles.user_id = (select auth.uid())
  )
);

drop policy if exists "Players and admins can delete drinks" on public.drinks;
create policy "Players and admins can delete drinks"
on public.drinks
for delete
to authenticated
using (
  owner_user_id = (select auth.uid())
  or (select public.is_admin())
);

grant usage on schema public to authenticated;
grant select on public.players to authenticated;
grant insert, update, delete on public.players to authenticated;
grant select, insert, update, delete on public.profiles to authenticated;
grant select on public.admins to authenticated;
grant select, insert, delete on public.drinks to authenticated;
grant usage, select on sequence public.drinks_id_seq to authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'players'
  ) then
    alter publication supabase_realtime add table public.players;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'drinks'
  ) then
    alter publication supabase_realtime add table public.drinks;
  end if;
end
$$;

-- Nadat je in Supabase een beheerdersaccount hebt gemaakt:
-- 1. Open Authentication, Users.
-- 2. Kopieer de UUID van jouw account.
-- 3. Voer deze regel apart uit met jouw echte UUID:
--
-- insert into public.admins (user_id)
-- values ('00000000-0000-0000-0000-000000000000');
